name: Auto Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Auto label based on files
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml

    - name: Label based on PR title
      uses: actions/github-script@v7
      with:
        script: |
          const title = context.payload.pull_request.title.toLowerCase();
          const labels = [];
          
          if (title.includes('feat:') || title.includes('feature:')) {
            labels.push('enhancement');
          }
          if (title.includes('fix:') || title.includes('bug:')) {
            labels.push('bug');
          }
          if (title.includes('docs:')) {
            labels.push('documentation');
          }
          if (title.includes('test:')) {
            labels.push('testing');
          }
          if (title.includes('ci:') || title.includes('cd:')) {
            labels.push('ci/cd');
          }
          if (title.includes('refactor:')) {
            labels.push('refactoring');
          }
          
          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: labels
            });
          }

    - name: Label PR size
      uses: actions/github-script@v7
      with:
        script: |
          const pr = context.payload.pull_request;
          const additions = pr.additions;
          const deletions = pr.deletions;
          const total = additions + deletions;
          
          let sizeLabel = '';
          if (total < 10) sizeLabel = 'size/XS';
          else if (total < 50) sizeLabel = 'size/S';
          else if (total < 200) sizeLabel = 'size/M';
          else if (total < 500) sizeLabel = 'size/L';
          else sizeLabel = 'size/XL';
          
          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: pr.number,
            labels: [sizeLabel]
          });
