name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 1'  
  push:
    branches: [ main, stab ]
    paths:
      - 'backend/requirements.txt'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
  workflow_dispatch:  

jobs:
  backend-deps:
    name: Backend Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install safety pip-audit

    - name: Check for security vulnerabilities with Safety
      working-directory: ./backend
      run: safety check --json
      continue-on-error: true

    - name: Audit dependencies with pip-audit
      working-directory: ./backend
      run: pip-audit
      continue-on-error: true

    - name: Check for outdated packages
      working-directory: ./backend
      run: pip list --outdated

  frontend-deps:
    name: Frontend Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run npm audit
      working-directory: ./frontend
      run: npm audit --audit-level=moderate
      continue-on-error: true

    - name: Check for outdated packages
      working-directory: ./frontend
      run: npm outdated
      continue-on-error: true

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      if: github.event_name == 'pull_request'
